name: Build wheels

on:
  push:
    branches: [ develop/main ]
  pull_request:
    branches: [ develop/main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-12", "ubuntu-20.04", "windows-2022"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2

      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          path: ./wheelhouse/*.whl
