name: Build

on:
  push:
    branches: [ develop/main, develop/3.10 ]
  pull_request: {}

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-11", "ubuntu-20.04", "windows-latest"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2

      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          path: ./wheelhouse/*.whl
